# Generated by Django 4.1.3 on 2023-10-14 02:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('day_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(10)])),
                ('add_day', models.IntegerField()),
            ],
            options={
                'ordering': ['add_day'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('time_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.day')),
            ],
            options={
                'ordering': ['day__day', 'time'],
            },
        ),
    ]
