# Generated by Django 4.2.4 on 2023-08-19 03:28

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('ConferenceID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30)])),
                ('Abbreviation', models.CharField(max_length=3, validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'ordering': ['Abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('DivisionID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=5, validators=[django.core.validators.MaxLengthValidator(5)])),
                ('ConferenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.conference')),
            ],
            options={
                'ordering': ['ConferenceID', 'Name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('GameID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Start_Time', models.DateTimeField()),
                ('Away_Score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('Home_Score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('Game_Status', models.CharField(blank=True, choices=[('N', 'Not Started'), ('1', '1Q'), ('2', '2Q'), ('1', '3Q'), ('4', '4Q'), ('F', 'Finished')], default='N', max_length=1)),
            ],
            options={
                'ordering': ['WeekID', 'Start_Time'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('SeasonID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2018)])),
            ],
            options={
                'ordering': ['Year'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('WeekID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)])),
                ('TimeStart', models.DateTimeField()),
                ('TimeEnd', models.DateTimeField()),
                ('SeasonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.season')),
            ],
        ),
        migrations.CreateModel(
            name='Tiebreaker',
            fields=[
                ('TiebreakerID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Tiebreaker_Points', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('Submit_Date', models.DateTimeField(default=datetime.datetime(2023, 8, 18, 22, 28, 22, 518430))),
                ('GameID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.game')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('WeekID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.week')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('TeamID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Abbreviation', models.CharField(max_length=3, validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(3)])),
                ('Location', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30)])),
                ('Name', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30)])),
                ('DivisionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.division')),
            ],
            options={
                'ordering': ['Location', 'Name'],
            },
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('PickID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Point', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('Submit_Date', models.DateTimeField(default=datetime.datetime(2023, 8, 18, 22, 28, 22, 518430))),
                ('GameID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.game')),
                ('TeamID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.team')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('WeekID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.week')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='Away_TeamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Away_TeamID', to='football.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='Home_TeamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Home_TeamID', to='football.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='WeekID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.week'),
        ),
    ]
