# Generated by Django 4.2.4 on 2023-09-10 02:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0002_alter_conference_options_alter_division_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 21, 43, 40, 945666)),
        ),
        migrations.AlterField(
            model_name='tiebreaker',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 21, 43, 40, 946667)),
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('total_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.week')),
            ],
        ),
    ]
