# Generated by Django 4.2.4 on 2023-09-10 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_alter_pick_submit_date_alter_tiebreaker_submit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='tiebreaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.tiebreaker'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 22, 3, 41, 617629)),
        ),
        migrations.AlterField(
            model_name='tiebreaker',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 22, 3, 41, 617629)),
        ),
    ]
