# Generated by Django 4.1.3 on 2023-10-14 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_total_tiebreaker_alter_pick_submit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 21, 13, 28, 727308)),
        ),
        migrations.AlterField(
            model_name='tiebreaker',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 21, 13, 28, 727308)),
        ),
    ]
