# Generated by Django 4.1.3 on 2023-11-11 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_alter_pick_submit_date_alter_tiebreaker_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='year_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 21, 51, 47, 897154)),
        ),
        migrations.AddField(
            model_name='season',
            name='year_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 21, 51, 47, 897154)),
        ),
        migrations.AlterField(
            model_name='pick',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 21, 51, 47, 897658)),
        ),
        migrations.AlterField(
            model_name='tiebreaker',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 21, 51, 47, 897658)),
        ),
    ]
