# Generated by Django 4.1.3 on 2023-11-24 03:44

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_alter_pick_submit_date_alter_season_year_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('day_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20)),
                ('add_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
            ],
        ),
        migrations.RemoveField(
            model_name='gametime',
            name='add_days',
        ),
        migrations.RemoveField(
            model_name='gametime',
            name='day_of_week',
        ),
        migrations.AlterField(
            model_name='pick',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 44, 50, 212163)),
        ),
        migrations.AlterField(
            model_name='season',
            name='year_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 44, 50, 212163)),
        ),
        migrations.AlterField(
            model_name='season',
            name='year_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 44, 50, 212163)),
        ),
        migrations.AlterField(
            model_name='tiebreaker',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 44, 50, 212163)),
        ),
        migrations.AddField(
            model_name='gametime',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='football.day'),
        ),
    ]
