# Generated by Django 4.1.3 on 2023-11-24 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_day_remove_gametime_add_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 46, 43, 731905)),
        ),
        migrations.AlterField(
            model_name='season',
            name='year_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 46, 43, 731905)),
        ),
        migrations.AlterField(
            model_name='season',
            name='year_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 46, 43, 731905)),
        ),
        migrations.AlterField(
            model_name='tiebreaker',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 21, 46, 43, 731905)),
        ),
    ]
